name: API CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        working-directory: ./qna-api
        run: npm ci
      
      - name: Contextualize environment
        uses: canastro/copy-file-action@master
        with:
          source: "qna-api/.env.ci"
          target: "qna-api/.env"
      
      - name: Start database
        working-directory: ./qna-api
        run: npm run db-start

      - name: Run api
        working-directory: ./qna-api
        run: npm test
